// src/app/models/ai-agent-config.ts

export interface AiAgentFieldConfig {
  required: boolean;
  editable: boolean;
  options?: { value: string | number | boolean; label: string }[];
  defaultValue?: any;
  type: 'string' | 'number' | 'boolean' | 'string[]';
  label: string;
  tooltip?: string; // Optional tooltip
  order: number;
}

export interface AiAgentTypeConfig {
  [fieldName: string]: AiAgentFieldConfig;
}

export const AI_AGENT_CONFIG: { [agentType: string]: AiAgentTypeConfig } = {
  teacher: {
    persona: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'The purpose, role, or identity of the AI. This is fixed.',
    },
    task: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Task',
      order: 2,
      tooltip: 'How the AI should behave or respond to prompts. This is fixed.',
    },
    topic: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip:
        'The topic of discussion or question that students are responding to.',
    }, // Fixed for teacher
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to. Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: false,
      type: 'string',
      options: [{ value: 'all', label: 'All' }],
      label: 'User Scope',
      order: 5,
      tooltip: 'This agent applies to the whole class.',
    },
    triggerEventTypes: {
      required: false,
      editable: false,
      type: 'string[]',
      options: [],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'This agent is triggered by user chat.',
    },
    eventThreshold: {
      required: false,
      editable: false,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip: 'This agent does not have a trigger theshold',
    },
    criteriaToGroupStudents: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'This agent does not regroup students.',
    },
    workflowsToActivate: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'This agent does not trigger workflows',
    },
    criteriaToActivateWorkflow: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'This agent does not use workflow activation criteria',
    },
    databaseWriteAccess: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      label: 'Database Write Access',
      order: 11,
      tooltip:
        'Allow the agent to write to the database (e.g., add or remove posts)?',
    },
    uiIntegrations: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'Workspace', label: 'Workspace' },
        { value: 'Canvas', label: 'Canvas' },
        { value: 'Bucket View', label: 'Bucket View' },
        { value: 'Monitor', label: 'Monitor' },
      ],
      label: 'AI Access Locations',
      order: 12,
      tooltip:
        'Locations where teachers can interact with the AI. Students cannot interact with this AI Agent',
    },
    enabled: {
      required: true,
      editable: false,
      type: 'boolean',
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'This agent is always enabled.',
    }, // ALWAYS TRUE, not editable
  },
  idea_chat: {
    persona: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'The purpose, role, or identity of the AI.  This is fixed',
    },
    task: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Task',
      order: 2,
      tooltip:
        'How the AI should behave or respond to prompts.  This is fixed.',
    },
    topic: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip: 'The topic for idea generation.',
    },
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to. Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: false,
      type: 'string',
      options: [{ value: 'all', label: 'All' }],
      label: 'User Scope',
      order: 5,
      tooltip: 'This agent applies to the whole class.',
    }, // Fixed for idea_chat
    triggerEventTypes: {
      required: false,
      editable: false,
      type: 'string[]',
      options: [],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'This agent is triggered by user chat.',
    },
    eventThreshold: {
      required: false,
      editable: false,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip: 'This agent does not have a trigger theshold',
    },
    criteriaToGroupStudents: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'This agent does not regroup students.',
    },
    workflowsToActivate: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'This agent does not trigger workflows',
    },
    criteriaToActivateWorkflow: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'This agent does not use workflow activation criteria',
    },
    databaseWriteAccess: {
      required: false,
      editable: false,
      type: 'boolean',
      label: 'Database Write Access',
      order: 11,
      tooltip: 'This agent cannot write to the database.',
    },
    uiIntegrations: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'AI Access Locations',
      order: 12,
      tooltip: 'This agent has no UI integrations.',
    },
    enabled: {
      required: true,
      editable: false,
      type: 'boolean',
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'This agent is always enabled.',
    }, // ALWAYS TRUE
  },
  idea_ambient: {
    persona: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'The purpose, role, or identity of the AI.  This is fixed',
    },
    task: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Task',
      order: 2,
      tooltip: 'How the AI should behave or respond to prompts. This is fixed.',
    },
    topic: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip: 'The topic for idea generation.',
    },
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to. Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: false,
      type: 'string',
      options: [{ value: 'all', label: 'All' }],
      label: 'User Scope',
      order: 5,
      tooltip: 'This agent applies to the whole class.',
    },
    triggerEventTypes: {
      required: true,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'POST_CREATE', label: 'Post Create' },
        { value: 'POST_COMMENT', label: 'Post Comment' },
        { value: 'POST_UPVOTE', label: 'Post Upvote' },
      ],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'Select the events that will trigger this agent.',
    },
    eventThreshold: {
      required: false,
      editable: false,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip: 'This agent does not have a trigger theshold',
    },
    criteriaToGroupStudents: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'This agent does not regroup students.',
    },
    workflowsToActivate: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'This agent does not trigger workflows',
    },
    criteriaToActivateWorkflow: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'This agent does not use workflow activation criteria',
    },
    databaseWriteAccess: {
      required: false,
      editable: false,
      type: 'boolean',
      label: 'Database Write Access',
      order: 11,
      tooltip: 'This agent cannot write to the database.',
    },
    uiIntegrations: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'AI Access Locations',
      order: 12,
      tooltip: 'This agent has no UI integrations.',
    },
    enabled: {
      required: true,
      editable: false,
      type: 'boolean',
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'This agent is always enabled.',
    }, // ALWAYS TRUE
  },
  personal_learning: {
    persona: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'Enter the purpose, role, or identity of the AI.',
    },
    task: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Task',
      order: 2,
      tooltip: 'Describe how the AI should behave or respond to prompts.',
    },
    topic: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip:
        'The topic of discussion or question that students are responding to.',
    },
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'canvas', label: 'Canvas' },
        { value: 'all', label: 'All' },
        { value: 'buckets', label: 'Buckets' },
      ],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to. Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: true,
      type: 'string',
      options: [
        { value: 'personal', label: 'Personal' },
        { value: 'all', label: 'All' },
      ],
      label: 'User Scope',
      order: 5,
      tooltip:
        'Select if the agent should respond to all users, or just a single user.',
    },
    triggerEventTypes: {
      required: false,
      editable: false,
      type: 'string[]',
      options: [],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'This agent is triggered by user chat.',
    },
    eventThreshold: {
      required: false,
      editable: false,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip: 'This agent does not have a trigger theshold',
    },
    criteriaToGroupStudents: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'This agent does not regroup students.',
    },
    workflowsToActivate: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'This agent does not trigger workflows',
    },
    criteriaToActivateWorkflow: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'This agent does not use workflow activation criteria',
    },
    databaseWriteAccess: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      label: 'Database Write Access',
      order: 11,
      tooltip: 'Allow the agent to write to the database?',
    },
    uiIntegrations: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'Workspace', label: 'Workspace' },
        { value: 'Canvas', label: 'Canvas' },
        { value: 'Bucket View', label: 'Bucket View' },
        { value: 'Monitor', label: 'Monitor' },
      ],
      label: 'AI Access Locations',
      order: 12,
      tooltip: 'Select where students can interact with the AI.',
    },
    enabled: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'Enable or disable this agent.',
    },
  },
  group_interaction: {
    persona: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'The purpose, role, or identity of the AI. This is fixed.',
    },
    task: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Task',
      order: 2,
      tooltip: 'Describe how the AI should behave or respond to prompts.',
    },
    topic: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip:
        'The topic of discussion or question that students are responding to.',
    },
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'canvas', label: 'Canvas' },
        { value: 'all', label: 'All' },
        { value: 'buckets', label: 'Buckets' },
      ],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to.  Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: false,
      type: 'string',
      options: [{ value: 'group', label: 'Group' }],
      label: 'User Scope',
      order: 5,
      tooltip: 'This agent applies to student groups.',
    },
    triggerEventTypes: {
      required: true,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'POST_CREATE', label: 'Post Create' },
        { value: 'POST_COMMENT', label: 'Post Comment' },
        { value: 'POST_UPVOTE', label: 'Post Upvote' },
        { value: 'POST_TAG', label: 'Post Tag' },
      ],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'Select the events that will trigger this agent.',
    },
    eventThreshold: {
      required: true,
      editable: true,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip:
        'The number of trigger events required before the AI Agent is triggered.',
    },
    criteriaToGroupStudents: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'This agent does not regroup students.',
    },
    workflowsToActivate: {
      required: false,
      editable: false,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'This agent does not trigger workflows',
    },
    criteriaToActivateWorkflow: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'This agent does not use workflow activation criteria',
    },
    databaseWriteAccess: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      label: 'Database Write Access',
      order: 11,
      tooltip: 'Allow the agent to write to the database?',
    },
    uiIntegrations: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'Workspace', label: 'Workspace' },
        { value: 'Canvas', label: 'Canvas' },
        { value: 'Bucket View', label: 'Bucket View' },
        { value: 'Monitor', label: 'Monitor' },
      ],
      label: 'AI Access Locations',
      order: 12,
      tooltip: 'Select where students can interact with the AI.',
    },
    enabled: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'Enable or disable this agent.',
    },
  },
  workflow: {
    persona: {
      required: false,
      editable: false,
      type: 'string',
      label: 'Persona',
      order: 1,
      tooltip: 'The purpose, role, or identity of the AI. This is fixed.',
    },
    task: {
      required: true,
      editable: true,
      type: 'string',
      options: [{ value: 'group students', label: 'Group Students' }],
      label: 'Task',
      order: 2,
      tooltip: 'Select what the agent will do.',
    },
    topic: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Topic',
      order: 3,
      tooltip:
        'The topic of discussion or question that students are responding to.',
    },
    payloadScope: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'canvas', label: 'Canvas' },
        { value: 'all', label: 'All' },
        { value: 'buckets', label: 'Buckets' },
      ],
      defaultValue: ['all'],
      label: 'Data Context',
      order: 4,
      tooltip:
        'Select the scope of data the agent will have access to. Select "All" or individual sources.',
    },
    userScope: {
      required: true,
      editable: false,
      type: 'string',
      options: [{ value: 'all', label: 'All' }],
      label: 'User Scope',
      order: 5,
      tooltip: 'This agent applies to all users.',
    },
    triggerEventTypes: {
      required: false,
      editable: false,
      type: 'string[]',
      options: [],
      label: 'Trigger Events',
      order: 6,
      tooltip: 'This agent is triggered manually.',
    },
    eventThreshold: {
      required: false,
      editable: false,
      type: 'number',
      label: 'Trigger Threshold',
      order: 7,
      tooltip: 'This agent does not have a trigger theshold',
    },
    criteriaToGroupStudents: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Grouping Criteria',
      order: 8,
      tooltip: 'Define criteria by which to group students',
    },
    workflowsToActivate: {
      required: true,
      editable: true,
      type: 'string[]',
      label: 'Workflows to Activate',
      order: 9,
      tooltip: 'Select workflows to activate',
    },
    criteriaToActivateWorkflow: {
      required: true,
      editable: true,
      type: 'string',
      label: 'Workflow Activation Criteria',
      order: 10,
      tooltip: 'Define criteria for activating workflows',
    },
    databaseWriteAccess: {
      required: true,
      editable: true,
      type: 'boolean',
      options: [
        { value: true, label: 'True' },
        { value: false, label: 'False' },
      ],
      label: 'Database Write Access',
      order: 11,
      tooltip: 'Allow the agent to write to the database?',
    },
    uiIntegrations: {
      required: false,
      editable: true,
      type: 'string[]',
      options: [
        { value: 'Workspace', label: 'Workspace' },
        { value: 'Canvas', label: 'Canvas' },
        { value: 'Bucket View', label: 'Bucket View' },
        { value: 'Monitor', label: 'Monitor' },
      ],
      label: 'AI Access Locations',
      order: 12,
      tooltip: 'Select where students can interact with the AI.',
    },
    enabled: {
      required: true,
      editable: false,
      type: 'boolean',
      defaultValue: true,
      label: 'Enabled',
      order: 13,
      tooltip: 'This agent is always enabled.',
    },
  },
};
