export enum SocketEvent {
  POST_CREATE = 'POST_CREATE',
  POST_DELETE = 'POST_DELETE',

  // POST_TITLE_CHANGE = 'POST_TITLE_CHANGE',
  // POST_DESC_CHANGE = 'POST_DESC_CHANGE',
  // POST_LIKE = 'POST_LIKE',
  // POST_COMMENT = 'POST_COMMENT',
  POST_START_MOVE = 'POST_START_MOVE',
  POST_STOP_MOVE = 'POST_STOP_MOVE',
  // POST_LOCK = 'POST_LOCK',
  // POST_NEEDS_ATTENTION_TAG = 'POST_NEEDS_ATTENTION_TAG',
  // POST_NO_TAG = 'POST_NO_TAG',

  // BOARD_BG_IMAGE_CHANGE = 'BOARD_BG_IMAGE_CHANGE',
  // BOARD_LOCK_POSTS = 'BOARD_LOCK_POSTS',
  // BOARD_UPDATE_VISIBILITY = 'BOARD_UPDATE_VISIBILITY',
  // BOARD_UPDATE_NAME = 'BOARD_UPDATE_NAME'
}